myBlog/Blog/urls.py
from django.urls import path
from Blog import views

app_name = 'Blog'

urlpatterns =[
    path('',views.Blog_list.as_view(),name='blog_list'),
    path('write/',views.CreateBlog.as_view(),name='create_blog'),
    path('details/<slug:slug>',views.blog_details,name='blog_details'),
    path('liked/<pk>/',views.liked,name='liked_post'),
    path('unliked/<pk>/',views.unliked,name='unliked_post'),
    path('my-blogs/',views.My_blog.as_view(),name='my_blogs'),
    path('edit/<pk>/',views.update_blog.as_view(),name='edit_blog'),

]

myBlog/LogIn/urls.py
from django.urls import path
from LogIn import views

app_name = 'LogIn'

urlpatterns =[
    path('SignUp/',views.SignUp,name='signup'),
    path('LogIn/',views.LogIn,name='login'),
    path('LogOut/',views.logout_user,name='logout'),
    path('Profile/',views.user_profile,name='profile'),
    path('Change_profile/',views.change_profile,name='change_profile'),
    path('password/',views.pass_change,name ='pass_change'),
    path('add-picture/',views.addpro_pic,name='addpro_pic'),
    path('change-picture/',views.change_pro_pic,name='change_pro_pic')

]

myBlog/myBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
# For media Profile
from django.conf import settings
from django.contrib.staticfiles.urls import  staticfiles_urlpatterns,static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('LogIn.urls')), # add account url
    path('blog/',include('Blog.urls')), # add blog url
    path('',views.Index,name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myBlog/LogIn/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User,related_name= 'user_profile',on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to ='profile_pic')
    

myBlog/LogIn/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import  User
from LogIn.models import UserProfile

class SignUp_form(UserCreationForm):

    email = forms.EmailField(required = True)

    class Meta:
        model = User
        fields = ('username','email','password1','password2')


class UserProfileChange(UserChangeForm):
    class Meta:
        model = User
        fields =('username','email','first_name','last_name','password')

class ProfilePic(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields =['profile_pic',]

myBlog/LogIn/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login, authenticate, logout # Function for authentication
from django.shortcuts import HttpResponseRedirect
from django.urls import  reverse
from django.contrib.auth.decorators import login_required
from LogIn.forms import SignUp_form , UserProfileChange,  ProfilePic

# Create your views here.

# Function for signup
def SignUp(request):
    form = SignUp_form()
    registered = False

    if request.method == 'POST':
        form = SignUp_form(data=request.POST)

        if form.is_valid():
            form.save()
            registered = True

    dict = {'form':form,'registered':registered}
    return render(request,'LogIn/signup.html',context=dict)



# Function for LogIn
def LogIn(request):
    form = AuthenticationForm()

    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(username=username,password=password)

            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

    return render(request,'LogIn/login.html',context={'form':form})

# Function for logout

@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def user_profile(request):
    return render(request,'LogIn/user_profile.html',context={})

@login_required
def change_profile(request):
    current_user = request.user
    form = UserProfileChange(instance = current_user)

    if request.method == "POST":
        form = UserProfileChange(request.POST,instance=current_user)
        if form.is_valid():
            form.save()
            form =UserProfileChange(instance=current_user)

    return render(request,"LogIn/change_profile.html",context={'form':form})

@login_required
def pass_change(request):
    current_user = request.user
    form = PasswordChangeForm(current_user)

    message = False

    if request.method == 'POST':
        form = PasswordChangeForm(current_user,data = request.POST)
        if form.is_valid():
            form.save()
            message = True

    return render(request,'LogIn/pass_change.html',context={'form':form,'message':message})

@login_required
def addpro_pic(request):
    form = ProfilePic()
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('LogIn:profile'))
    return render(request,'LogIn/pro_pic_add.html',context={'form':form})

@login_required
def change_pro_pic(request):
    form = ProfilePic(instance=request.user.user_profile)
    if request.method == "POST":
        form = ProfilePic(request.POST, request.FILES,instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('LogIn:profile'))


    return render(request,'LogIn/pro_pic_add.html',context={'form':form})

myBlog/templates/LogIn/change_profile.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block title_block %}Change Profile{% endblock %}
{% block body_block %}
<h2>Change Profile</h2>
<form method="post">
  {{form|crispy}}
  {% csrf_token %}
  <button type="submit" class="btn btn-warning btn-sm">Change</button>
</form>



{% endblock %}

myBlog/templates/LogIn/login.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block title_block %}LogIn{% endblock %}
{% block body_block %}
<h2>LogIn</h2>
<form method="post">
  {{form|crispy}}
  {% csrf_token %}
  <button type="submit" class="btn btn-primary btn-sm">LogIn</button>
</form>



{% endblock %}

myBlog/templates/LogIn/pass_change.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block title_block %}Change Password{% endblock %}
{% block body_block %}
<h2>Change Profile</h2>

{% if message %}
<div class="alert alert-success">
  Password Changed Successfully !

</div>
{% endif %}
<form method="post">
  {{form|crispy}}
  {% csrf_token %}
  <button type="submit" class="btn btn-warning btn-sm">Change</button>
</form>



{% endblock %}

myBlog/templates/LogIn/pro_pic_add.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block title_block %}Add profile picture{% endblock %}
{% block body_block %}
<h2>Add your profile picture</h2>
<form method="POST" enctype="multipart/form-data">
  {{form|crispy}}
  {% csrf_token %}
  <button type="submit" class="btn btn-success btn-sm">Change</button>
</form>



{% endblock %}

myBlog/templates/LogIn/signup.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block title_block %}SignUp{% endblock %}

{% block body_block %}

{% if registered %}

<div class="alert alert-success">
  <p>Account Created successfully <a href="{% url 'LogIn:login' %}">LogIn Here</a></p>
</div>

{% else %}

<h2>Create New Account</h2>
<form method='POST'>
  {{ form|crispy }}
  {% csrf_token %}

  <button type="submit" class="btn btn-success btn-sm">Create Account</button>
</form>

<br>

<p>Already have an account <a href="{% url 'LogIn:login' %}">LogIn Here</a></p>


{% endif %}
{% endblock %}

myBlog/templates/LogIn/user_profile.html
{% extends 'base.html' %}
{% block title_block %}Profile{% endblock %}
{% block body_block %}

<h2>Your Profile</h2>

{% if user.user_profile %}
<img src="/media/{{user.user_profile.profile_pic}}" class="rounded-circle" width="100px">
<br>
<br>
<a href="{% url 'LogIn:change_pro_pic' %}" class="btn btn-info btn-sm">Change Profile</a>
{% else %}
<img src="/media/profile_pic/profile_pic.png" class="rounded-circle" width="100px">
<br>
<br>
<a href="{% url 'LogIn:addpro_pic' %}" class="btn btn-info btn-sm">Change Profile</a>
<br>
{% endif %}

<p>Username: {{user.username}} </p>
<p>Email: {{user.email}}</p>
<p>Name : {{user.first_name}} {{user.last_name}}</p>

<br>

<a href="{% url 'LogIn:change_profile' %} " class="btn btn-warning btn-sm">Change_profile_info</a>
{% endblock %}