myBlog/Blog/urls.py
from django.urls import path
from Blog import views

app_name = 'Blog'

urlpatterns =[
    path('',views.Blog_list.as_view(),name='blog_list'),
    path('write/',views.CreateBlog.as_view(),name='create_blog'),
    path('details/<slug:slug>',views.blog_details,name='blog_details'),
    path('liked/<pk>/',views.liked,name='liked_post'),
    path('unliked/<pk>/',views.unliked,name='unliked_post'),
    path('my-blogs/',views.My_blog.as_view(),name='my_blogs'),
    path('edit/<pk>/',views.update_blog.as_view(),name='edit_blog'),

]

myBlog/LogIn/urls.py
from django.urls import path
from LogIn import views

app_name = 'LogIn'

urlpatterns =[
    path('SignUp/',views.SignUp,name='signup'),
    path('LogIn/',views.LogIn,name='login'),
    path('LogOut/',views.logout_user,name='logout'),
    path('Profile/',views.user_profile,name='profile'),
    path('Change_profile/',views.change_profile,name='change_profile'),
    path('password/',views.pass_change,name ='pass_change'),
    path('add-picture/',views.addpro_pic,name='addpro_pic'),
    path('change-picture/',views.change_pro_pic,name='change_pro_pic')

]

myBlog/myBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
# For media Profile
from django.conf import settings
from django.contrib.staticfiles.urls import  staticfiles_urlpatterns,static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('LogIn.urls')), # add account url
    path('blog/',include('Blog.urls')), # add blog url
    path('',views.Index,name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myBlog/Blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# Model for blog
class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=300, verbose_name='Put a title')
    slug = models.SlugField(max_length=300, unique=True)
    blog_content = models.TextField(verbose_name='What is on your mind?')
    blog_image = models.ImageField(upload_to = 'blog_images',verbose_name='Images')
    publish_date = models.DateTimeField(auto_now_add = True)
    update_date = models.DateTimeField(auto_now = True)

    class  Meta:
        ordering = ('-publish_date',)

    def __str__(self):
        return self.blog_title


# Model for comment
class Comment(models.Model):
    blog = models.ForeignKey(Blog,on_delete=models.CASCADE,related_name='blog_comment')
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_comment')
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)
    comment_date_update = models.DateTimeField(auto_now=True)

    class  Meta:
        ordering = ('-comment_date',)

    def __str__(self):
        return self.comment

# Model for likes

class Likes(models.Model):
    blog = models.ForeignKey(Blog,on_delete = models.CASCADE,related_name='liked_blog')
    user = models.ForeignKey(User,on_delete = models.CASCADE,related_name='liker_user')

myBlog/Blog/forms.py
from django import forms
from Blog.models import Comment,Blog

class CommentForm(forms.ModelForm):
    class  Meta:
        model = Comment
        fields = ('comment',)
        

myBlog/Blog/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import CreateView,UpdateView,DetailView,ListView,DetailView,TemplateView,View
from Blog.models import Blog ,Comment, Likes
from django.urls import reverse,reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from Blog.forms import CommentForm
import uuid


# Create your views here.

# def blog_list(request):
#     return render(request,'Blog/blog_list.html',context={})


class My_blog(LoginRequiredMixin, TemplateView):
    template_name = 'Blog/my_blog.html'

class update_blog(LoginRequiredMixin,UpdateView):
    model = Blog
    fields =('blog_title','blog_content','blog_image')
    template_name = 'Blog/edit_blog.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('Blog:blog_details',kwargs={'slug':self.object.slug})



class Blog_list(ListView):
    context_object_name = 'Blogs'
    model = Blog
    template_name = 'Blog/blog_list.html'

    # for desending prder
    #queryset = Blog.objects.order_by('-publish_date')


class CreateBlog(LoginRequiredMixin,CreateView):
    model = Blog
    template_name = 'Blog/create_blog.html'
    fields =('blog_title','blog_content','blog_image',)

    def form_valid(self,form):
        blog_object = form.save(commit = False)
        blog_object.author = self.request.user
        title = blog_object.blog_title
        blog_object.slug = title.replace(" ", "-") + "-" + str(uuid.uuid4())
        blog_object.save()
        return HttpResponseRedirect(reverse('index'))

@login_required
def blog_details(request, slug):
    blog = Blog.objects.get(slug=slug)
    comment_form = CommentForm()
    already_liked = Likes.objects.filter(blog=blog,user= request.user)
    if already_liked:
        liked = True
    else:
        liked = False

    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.blog = blog
            comment.save()
            return HttpResponseRedirect(reverse('Blog:blog_details',kwargs={'slug':slug}))
    return render(request,'Blog/blog_details.html',context={'blog':blog,'comment_form':comment_form,'liked':liked})

@login_required
def liked(request,pk):

    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog,user = user)

    if not already_liked:
        liked_post = Likes(blog=blog,user=user)
        liked_post.save()
    return HttpResponseRedirect(reverse('Blog:blog_details',kwargs={'slug':blog.slug}))


@login_required
def unliked(request,pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog,user = user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('Blog:blog_details',kwargs={'slug':blog.slug}))

myBlog/myBlog/views.py
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import HttpResponseRedirect


def Index(request):
    return HttpResponseRedirect(reverse('Blog:blog_list'))

myBlog/templates/Blog/blog_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title_block %} {{blog.blog_title}} {% endblock %}

{% block body_block %}
<div class="row">
  <div class="col-sm-6">
    <h2>{{blog.blog_title}}</h2>
    <h4>Posted By : @{{blog.author}}</h4>
    <i>
      <h6>Published on : {{blog.publish_date}}</h6>
    </i>
    <i>
      <h6>Updated on : {{blog.update_date}}</h6>
    </i>

    <h6>{{blog.liked_blog.count}} Likes |{{blog.blog_comment.count}} Comments</h6>

  </div>

  <div class="col-sm-6">
    <img src="/media/{{blog.blog_image}}" width="100%">

  </div>
  <p>{{blog.blog_content|linebreaks}}</p>
  <hr>

</div>
{% if not liked %}
<a href="{% url 'Blog:liked_post' pk=blog.pk %}">
  <i class="fa fa-thumbs-o-up fa-2x" aria-hidden="true"></i>
</a>
{% else %}
<a href="{% url 'Blog:unliked_post' pk=blog.pk %}">
  <i class="fa fa-thumbs-o-down fa-2x" aria-hidden="true"></i>
</a>
{% endif %}
<div class="row">
  <div class="col-sm-6">
    <hr>
    <h5>Comments</h5>
    {% for comment in blog.blog_comment.all %}
    <p><a href="#">@{{comment.user}}</a> {{comment.comment}}<br>
    <h6>{{comment.comment_date}}</h6>
    </p>
    {% endfor %}
  </div>

  <div class="col-sm-6">
    <form method="POST">

      {{ comment_form|crispy }}
      {% csrf_token %}

      <button type="submit" class="btn btn-primary btn-sm">Comment</button>
    </form>

  </div>

</div>
<br>
<br>
{% endblock %}

myBlog/templates/Blog/blog_list.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block title_block %}Home{% endblock %}

{% block body_block %}

{% for blog in Blogs %}
<h3>{{ blog.blog_title }}</h3>
<h6>{{ blog.publish_date }}</h6>

<div class="row">
  <div class="col-sm-4">
    <img src="/media/{{blog.blog_image}}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}" width="100%">

  </div>
  <div class="col-sm-8">
    <p>{{blog.blog_content|range_filter|linebreaks}}<a href="{% url 'Blog:blog_details' slug=blog.slug %}">Read More</a></p>
    <h6>Posted By : <a href="{% url 'LogIn:profile' %}">@{{blog.author}}</a></h6>
    <h6>{{blog.liked_blog.count}} Likes |{{blog.blog_comment.count}} Comments</h6>

  </div>

</div>
<hr>
{% endfor %}


{% endblock %}

myBlog/templates/Blog/create_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {% endblock %}
{% block body_block %}
<h2>Write Your Blog Here:</h2>
<form method="POST" enctype="multipart/form-data">
  {{ form|crispy }}
  {% csrf_token %}
  <button type="submit" class="btn btn-success btn-sm">Publish</button>
</form>
{% endblock %}

myBlog/templates/Blog/edit_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{blog.blog_title}} {% endblock %}
{% block body_block %}
{% if blog.author == user %}
<form method="POST">
  {{form|crispy}}
  {% csrf_token %}
  <button type="submit" name="button">Update</button>
  {% else %}
  <p>Your are not allowed to view this page. 404</p>
</form>
{% endif %}
{% endblock %}

myBlog/templates/Blog/my_blog.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block title_block %} {{user}} {% endblock %}


{% block body_block %}

{% for blog in user.post_author.all %}

<h3>{{blog.blog_title}}</h3>
<h6>{{blog.publish_date}}</h6>
<div class="row">
  <div class="col-sm-4">
    <img src="/media/{{blog.blog_image}}" width="100%">
  </div>
  <div class="col-sm-8">
    <p>{{blog.blog_content|range_filter|linebreaks}}</p>
    <a href="{% url 'Blog:blog_details' slug=blog.slug %}">Read More</a>
  </div>
</div>
<a href="{% url 'Blog:edit_blog' pk=blog.pk %}">Edit</a>
<hr>

{% endfor %}

{% endblock %}