myBlog/Blog/urls.py
from django.urls import path
from Blog import views

app_name = 'Blog'

urlpatterns =[
    path('',views.Blog_list.as_view(),name='blog_list'),
    path('write/',views.CreateBlog.as_view(),name='create_blog'),
    path('details/<slug:slug>',views.blog_details,name='blog_details'),
    path('liked/<pk>/',views.liked,name='liked_post'),
    path('unliked/<pk>/',views.unliked,name='unliked_post'),
    path('my-blogs/',views.My_blog.as_view(),name='my_blogs'),
    path('edit/<pk>/',views.update_blog.as_view(),name='edit_blog'),

]

myBlog/LogIn/urls.py
from django.urls import path
from LogIn import views

app_name = 'LogIn'

urlpatterns =[
    path('SignUp/',views.SignUp,name='signup'),
    path('LogIn/',views.LogIn,name='login'),
    path('LogOut/',views.logout_user,name='logout'),
    path('Profile/',views.user_profile,name='profile'),
    path('Change_profile/',views.change_profile,name='change_profile'),
    path('password/',views.pass_change,name ='pass_change'),
    path('add-picture/',views.addpro_pic,name='addpro_pic'),
    path('change-picture/',views.change_pro_pic,name='change_pro_pic')

]

myBlog/myBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
# For media Profile
from django.conf import settings
from django.contrib.staticfiles.urls import  staticfiles_urlpatterns,static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('LogIn.urls')), # add account url
    path('blog/',include('Blog.urls')), # add blog url
    path('',views.Index,name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myBlog/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <title>{% block title_block %}Home{% endblock %}</title>

</head>


<body>
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}">Home</a>
      </li>
      {% if user.is_authenticated %}
      <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbardrop" data-toggle="dropdown">
          @{{user.username}}
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{% url 'LogIn:profile' %}">Profile</a>
          <a class="dropdown-item" href="{% url 'Blog:my_blogs' %}">MyBlogs</a>
          <a class="dropdown-item" href="{% url 'Blog:create_blog' %}">Create Blog</a>
          <hr>
          <a class="dropdown-item" href="{% url 'LogIn:logout' %}">LogOut</a>

        </div>
      </div>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'LogIn:signup' %}">SignUp</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'LogIn:login' %}">LogIn</a>
      </li>
      {% endif %}

    </ul>
  </nav>

  <div class="container" ,style="padding-top:20px">
    {% block body_block %}

    {% endblock %}
  </div>


</body>

</html>